import {
  NeuronActivationVis,
  ForwardBackpropVis,
  InitGradientFlowVis,
  NormDropoutVis,
  OptimizerVis,
  ResidualVis,
  CNNPoolingVis,
  RNNVis,
  AttentionVis,
  TransformerVis,
  EmbeddingVis,
  LossLandscapeVis,
} from "./deepLearningVisuals";

export const VIS_MAP = {
  perceptron: NeuronActivationVis,
  activations: [
    { id: "neuron-gate", label: "Neuron Gate", component: NeuronActivationVis },
    {
      id: "forward-flow",
      label: "Forward Flow",
      component: ForwardBackpropVis,
    },
  ],
  forwardpass: ForwardBackpropVis,
  backprop: ForwardBackpropVis,
  softmax: NeuronActivationVis,
  initialization: InitGradientFlowVis,
  vanishing: InitGradientFlowVis,
  batchnorm: NormDropoutVis,
  dropout: NormDropoutVis,
  layernorm: NormDropoutVis,
  gradientclipping: InitGradientFlowVis,
  earlystopping: LossLandscapeVis,
  dataaugmentation: CNNPoolingVis,
  sgd: OptimizerVis,
  adam: OptimizerVis,
  learningrate: OptimizerVis,
  finetuning: OptimizerVis,
  distillation: AttentionVis,
  mixedprecision: ForwardBackpropVis,
  weightdecay: [
    { id: "optimizer", label: "Optimizer Path", component: OptimizerVis },
    { id: "landscape", label: "Landscape", component: LossLandscapeVis },
  ],
  losslandscape: LossLandscapeVis,
  cnn: CNNPoolingVis,
  pooling: CNNPoolingVis,
  residual: ResidualVis,
  rnn: RNNVis,
  attention: AttentionVis,
  transformer: TransformerVis,
  embeddings: EmbeddingVis,
  transferlearning: EmbeddingVis,
  positionalencoding: TransformerVis,
  maskedattention: AttentionVis,
  encoderdecoder: TransformerVis,
  autoregressive: RNNVis,
  moe: TransformerVis,
  diffusion: LossLandscapeVis,
  prompttuning: EmbeddingVis,
  lstm: RNNVis,
  gru: RNNVis,
  bidirectional: RNNVis,
  beamsearch: TransformerVis,
  teacherforcing: RNNVis,
  labelsmoothing: NeuronActivationVis,
  focalloss: LossLandscapeVis,
  contrastivelearning: EmbeddingVis,
  metriclearning: EmbeddingVis,
  selfsupervised: EmbeddingVis,
  maskedmodeling: AttentionVis,
  vae: EmbeddingVis,
  gan: LossLandscapeVis,
  normalizingflows: ForwardBackpropVis,
  scorematching: LossLandscapeVis,
  lora: ResidualVis,
  quantization: ForwardBackpropVis,
  pruning: ResidualVis,
  flashattention: AttentionVis,
  retrievalaugmented: TransformerVis,
};
