import {
  MDPGraphVis,
  ReturnDiscountVis,
  BellmanBackupVis,
  TDUpdateVis,
  QTableVis,
  DQNSystemVis,
  PolicyGradientVis,
  ActorCriticVis,
  ModelPlanningVis,
  DataRegimeVis,
  BanditVis,
  ExplorationRewardVis,
  MultiAgentVis,
  HierarchyVis,
  BeliefStateVis,
  SafeRLVis,
  ImitationVis,
} from "./rlVisuals";

export const VIS_MAP = {
  mdp: MDPGraphVis,
  return: ReturnDiscountVis,
  bellman: BellmanBackupVis,
  policyevaluation: BellmanBackupVis,
  valueiteration: BellmanBackupVis,
  temporaldifference: TDUpdateVis,
  qlearning: QTableVis,
  dqn: DQNSystemVis,
  distributionalrl: [
    { id: "q-dist", label: "Q Distribution", component: QTableVis },
    { id: "backup-view", label: "Distribution Backup", component: BellmanBackupVis },
  ],
  policygradient: PolicyGradientVis,
  actorcritic: ActorCriticVis,
  ppo: ActorCriticVis,
  entropyrl: PolicyGradientVis,
  modelbasedrl: ModelPlanningVis,
  mcts: ModelPlanningVis,
  worldmodels: ModelPlanningVis,
  onpolicy: DataRegimeVis,
  offpolicy: DataRegimeVis,
  offlinerl: DataRegimeVis,
  imitationlearning: ImitationVis,
  bandits: BanditVis,
  intrinsicmotivation: ExplorationRewardVis,
  rewardshaping: ExplorationRewardVis,
  multiagentrl: MultiAgentVis,
  hierarchicalrl: HierarchyVis,
  options: HierarchyVis,
  pomdp: BeliefStateVis,
  saferl: SafeRLVis,
};
