import {
  MDPGraphVis,
  ReturnDiscountVis,
  BellmanBackupVis,
  TDUpdateVis,
  QTableVis,
  DQNSystemVis,
  PolicyGradientVis,
  ActorCriticVis,
  ModelPlanningVis,
  DataRegimeVis,
  BanditVis,
  ExplorationRewardVis,
  MultiAgentVis,
  HierarchyVis,
  BeliefStateVis,
  SafeRLVis,
  ImitationVis,
  SARSAVis,
  NStepVis,
  EligibilityTraceVis,
  DoubleDQNVis,
  DuelingDQNVis,
  PrioritizedReplayVis,
  DDPGVis,
  TD3Vis,
  SACVis,
  GAEVis,
  IRLVis,
  RLHFVis,
  MetaRLVis,
  CurriculumVis,
} from "./rlVisuals";

export const VIS_MAP = {
  mdp: MDPGraphVis,
  return: ReturnDiscountVis,
  bellman: BellmanBackupVis,
  policyevaluation: BellmanBackupVis,
  valueiteration: BellmanBackupVis,
  temporaldifference: TDUpdateVis,
  qlearning: QTableVis,
  dqn: DQNSystemVis,
  distributionalrl: [
    { id: "q-dist", label: "Q Distribution", component: QTableVis },
    { id: "backup-view", label: "Distribution Backup", component: BellmanBackupVis },
  ],
  policygradient: PolicyGradientVis,
  actorcritic: ActorCriticVis,
  ppo: ActorCriticVis,
  entropyrl: PolicyGradientVis,
  modelbasedrl: ModelPlanningVis,
  mcts: ModelPlanningVis,
  worldmodels: ModelPlanningVis,
  onpolicy: DataRegimeVis,
  offpolicy: DataRegimeVis,
  offlinerl: DataRegimeVis,
  imitationlearning: ImitationVis,
  bandits: BanditVis,
  intrinsicmotivation: ExplorationRewardVis,
  rewardshaping: ExplorationRewardVis,
  multiagentrl: MultiAgentVis,
  hierarchicalrl: HierarchyVis,
  options: HierarchyVis,
  pomdp: BeliefStateVis,
  saferl: SafeRLVis,
  sarsa: SARSAVis,
  nstep: NStepVis,
  eligibility: EligibilityTraceVis,
  doubledqn: DoubleDQNVis,
  duelingdqn: DuelingDQNVis,
  prioritizedreplay: PrioritizedReplayVis,
  ddpg: DDPGVis,
  td3: TD3Vis,
  sac: SACVis,
  trpo: ActorCriticVis,
  gae: GAEVis,
  irl: IRLVis,
  rlhf: RLHFVis,
  metarl: MetaRLVis,
  curriculum: CurriculumVis,
};
