import {
  PartialsVis,
  GradientVis,
  GradientFieldVis,
  DirectionalVis,
  TangentPlaneVis,
  JacobianVis,
  JacobianLinearizationVis,
  ChainRuleVis,
  ChangeVarsVis,
  HessianVis,
  CriticalPointsVis,
  Taylor2Vis,
  LagrangeVis,
  DivergenceVis,
  CurlVis,
  LineIntegralVis,
  LineIntegralConservativeVis,
  GreensTheoremVis,
  DoubleIntegralVis,
  DoubleIntegralOrderVis,
  TripleIntegralVis,
  SurfaceIntegralVis,
} from "./multivariableVisuals";

export const VIS_MAP = {
  partials: PartialsVis,
  gradient: [
    { id: "contour-normal", label: "Contour Normal", component: GradientVis },
    {
      id: "vector-field",
      label: "Gradient Field",
      component: GradientFieldVis,
    },
  ],
  directional: DirectionalVis,
  tangentplane: TangentPlaneVis,
  jacobian: [
    { id: "local-map", label: "Local Map", component: JacobianVis },
    {
      id: "linearization",
      label: "Linearization Error",
      component: JacobianLinearizationVis,
    },
  ],
  chainrule: ChainRuleVis,
  changevars: ChangeVarsVis,
  hessian: HessianVis,
  criticalpoints: CriticalPointsVis,
  taylor2: Taylor2Vis,
  lagrange: LagrangeVis,
  divergence: DivergenceVis,
  curl: CurlVis,
  lineintegral: [
    { id: "accumulation", label: "Accumulation", component: LineIntegralVis },
    {
      id: "path-independence",
      label: "Conservative Case",
      component: LineIntegralConservativeVis,
    },
  ],
  greentheorem: GreensTheoremVis,
  doubleintegral: [
    {
      id: "riemann-cells",
      label: "Riemann Cells",
      component: DoubleIntegralVis,
    },
    {
      id: "integration-order",
      label: "Order Swap",
      component: DoubleIntegralOrderVis,
    },
  ],
  tripleintegral: TripleIntegralVis,
  surfaceintegral: SurfaceIntegralVis,
};
