import {
  MeanMedianVis,
  MeanOutlierVis,
  SpreadVis,
  VarianceSquaresVis,
  CovarianceVis,
  CorrelationVis,
  DistributionVis,
  RandomVariableVis,
  ExpectationVis,
  PMFVis,
  CDFVis,
  ConditionalProbVis,
  IndependenceVis,
  NormalVis,
  EmpiricalRuleVis,
  ZScoreVis,
  LLNVis,
  CLTVis,
  BayesVis,
  LikelihoodVis,
  CredibleIntervalVis,
  PosteriorPredictiveVis,
  SamplingVis,
  BootstrapVis,
  ConfidenceVis,
  HypothesisVis,
  PValueVis,
  TTestVis,
  ANOVAVis,
  LinearRegVis,
  LogisticVis,
} from "./statisticsVisuals";

export const VIS_MAP = {
  mean: [
    { id: "mean-vs-median", label: "Mean vs Median", component: MeanMedianVis },
    {
      id: "outlier-sensitivity",
      label: "Outlier Sensitivity",
      component: MeanOutlierVis,
    },
  ],
  median: [
    { id: "rank-center", label: "Rank Center", component: MeanMedianVis },
  ],
  variance: [
    { id: "spread-band", label: "Spread Band", component: SpreadVis },
    {
      id: "squared-distance",
      label: "Squared Distances",
      component: VarianceSquaresVis,
    },
  ],
  stddev: [{ id: "unit-spread", label: "Unit Spread", component: SpreadVis }],
  covariance: CovarianceVis,
  correlation: CorrelationVis,
  distribution: DistributionVis,
  randomvar: RandomVariableVis,
  expectation: ExpectationVis,
  pmf: PMFVis,
  cdf: CDFVis,
  conditionalprob: ConditionalProbVis,
  independence: IndependenceVis,
  normal: [
    { id: "bell-curve", label: "Bell Curve", component: NormalVis },
    { id: "empirical-rule", label: "68-95-99.7", component: EmpiricalRuleVis },
  ],
  zscore: ZScoreVis,
  lln: LLNVis,
  clt: CLTVis,
  bayes: BayesVis,
  likelihood: LikelihoodVis,
  credible: CredibleIntervalVis,
  posteriorpredictive: PosteriorPredictiveVis,
  sampling: SamplingVis,
  bootstrap: BootstrapVis,
  confidence: ConfidenceVis,
  hypothesis: HypothesisVis,
  pvalue: PValueVis,
  ttest: TTestVis,
  anova: ANOVAVis,
  linearreg: LinearRegVis,
  logistic: LogisticVis,
};
