import {
  VectorNormProjectionVis,
  DotProductAngleVis,
  MatrixTransformVis,
  RankCompressionVis,
  EigenSVDPCAVis,
  DerivativeGradientVis,
  JacobianFieldVis,
  HessianConvexityVis,
  GradientDescentPathVis,
  ProbabilityExpectationVis,
  VarianceCovarianceVis,
  InformationTheoryVis,
  RegularizationVis,
  BiasVarianceVis,
  MLEVis,
} from "./mlMathVisuals";

export const VIS_MAP = {
  vectors: VectorNormProjectionVis,
  dotproduct: DotProductAngleVis,
  norms: [
    {
      id: "norm-geometry",
      label: "Norm Geometry",
      component: VectorNormProjectionVis,
    },
    { id: "alignment-view", label: "Alignment", component: DotProductAngleVis },
  ],
  projection: DotProductAngleVis,
  matrixmultiply: MatrixTransformVis,
  rank: RankCompressionVis,
  eigenspectrum: EigenSVDPCAVis,
  svd: EigenSVDPCAVis,
  pca: EigenSVDPCAVis,
  leastsquares: DotProductAngleVis,
  normalequation: MatrixTransformVis,
  pseudoinverse: MatrixTransformVis,
  conditioning: RankCompressionVis,
  derivative: DerivativeGradientVis,
  gradient: DerivativeGradientVis,
  jacobian: JacobianFieldVis,
  hessian: HessianConvexityVis,
  convexity: HessianConvexityVis,
  gradientdescent: GradientDescentPathVis,
  featurescaling: GradientDescentPathVis,
  randomvariable_ml: ProbabilityExpectationVis,
  expectation_ml: ProbabilityExpectationVis,
  variance_ml: VarianceCovarianceVis,
  covariance_ml: VarianceCovarianceVis,
  mapestimation: MLEVis,
  gmm: VarianceCovarianceVis,
  em: MLEVis,
  naivebayes: ProbabilityExpectationVis,
  entropy: InformationTheoryVis,
  crossentropy: InformationTheoryVis,
  kl: InformationTheoryVis,
  regularization: RegularizationVis,
  biasvariance: BiasVarianceVis,
  mle: MLEVis,
  kernels: DotProductAngleVis,
  ridge: RegularizationVis,
  lasso: RegularizationVis,
  elasticnet: RegularizationVis,
  svmmargin: DotProductAngleVis,
  knn: VectorNormProjectionVis,
  kmeans: VarianceCovarianceVis,
};
