import { MATRICES_DOMAIN } from "./matrices";
import { MULTIVARIABLE_DOMAIN } from "./multivariable";
import { ML_MATH_DOMAIN } from "./ml-math";
import { DEEP_LEARNING_DOMAIN } from "./deep-learning";
import { REINFORCEMENT_LEARNING_DOMAIN } from "./reinforcement-learning";
import { STATISTICS_DOMAIN } from "./statistics";
import { BAYESIAN_DOMAIN } from "./bayesian";
import { ACTIVATION_FUNCTIONS_DOMAIN } from "./activation-functions";
import { GPU_DOMAIN } from "./gpu";

export {
  MATRICES_DOMAIN,
  MULTIVARIABLE_DOMAIN,
  ML_MATH_DOMAIN,
  DEEP_LEARNING_DOMAIN,
  REINFORCEMENT_LEARNING_DOMAIN,
  STATISTICS_DOMAIN,
  BAYESIAN_DOMAIN,
  ACTIVATION_FUNCTIONS_DOMAIN,
  GPU_DOMAIN,
};

export const ALL_DOMAINS = [
  MATRICES_DOMAIN,
  MULTIVARIABLE_DOMAIN,
  ML_MATH_DOMAIN,
  DEEP_LEARNING_DOMAIN,
  REINFORCEMENT_LEARNING_DOMAIN,
  STATISTICS_DOMAIN,
  BAYESIAN_DOMAIN,
  ACTIVATION_FUNCTIONS_DOMAIN,
  GPU_DOMAIN,
];
