import {
  SMVis,
  WarpVis,
  ThreadHierarchyVis,
  TensorCoreVis,
  MemoryHierarchyVis,
  SIMTVis,
  WarpDivergenceVis,
  OccupancyVis,
  LatencyHidingVis,
  CoalescingVis,
  BankConflictsVis,
  RooflineVis,
  TilingVis,
  PipeliningVis,
  FlashAttentionVis,
  KernelLaunchVis,
  CUDAStreamsVis,
  TritonTilesVis,
  ArithmeticIntensityVis,
} from "./gpuVisuals";

export const VIS_MAP = {
  sm: SMVis,
  warp: WarpVis,
  thread_hierarchy: ThreadHierarchyVis,
  tensor_cores: TensorCoreVis,
  memory_hierarchy: MemoryHierarchyVis,
  simt: SIMTVis,
  warp_divergence: WarpDivergenceVis,
  occupancy: OccupancyVis,
  latency_hiding: LatencyHidingVis,
  global_memory: MemoryHierarchyVis,
  shared_memory: TilingVis,
  registers: OccupancyVis,
  coalescing: CoalescingVis,
  bank_conflicts: BankConflictsVis,
  kernel_launch: KernelLaunchVis,
  thread_indexing: KernelLaunchVis,
  synchronization: WarpVis,
  cuda_streams: CUDAStreamsVis,
  atomic_ops: WarpDivergenceVis,
  triton_model: TritonTilesVis,
  triton_tiles: TritonTilesVis,
  triton_ops: TilingVis,
  triton_autotuning: RooflineVis,
  roofline: RooflineVis,
  arithmetic_intensity: ArithmeticIntensityVis,
  tiling: TilingVis,
  pipelining: PipeliningVis,
  naive_gemm: TilingVis,
  tiled_gemm: TilingVis,
  tensor_core_gemm: TensorCoreVis,
  flash_attention: FlashAttentionVis,
};
