import {
  ObjectsMorphismsVis,
  CategoriesVis,
  CompositionVis,
  IdentityVis,
  IsomorphismVis,
  MonoVis,
  EpiVis,
  TerminalVis,
  ProductVis,
  CoproductVis,
  PullbackVis,
  EqualizerVis,
  FunctorVis,
  NaturalVis,
  AdjunctionVis,
  LimitsVis,
  MonadVis,
  YonedaVis,
  CCCVis,
  MonoidalVis,
  StringVis,
  ApplicativeVis,
  ProfunctorVis,
  ComonadVis,
  KanVis,
  PresheafVis,
  AbelianVis,
} from "./categoryTheoryVisuals";

export const VIS_MAP = {
  objects: ObjectsMorphismsVis,
  categories: CategoriesVis,
  composition: CompositionVis,
  identity: IdentityVis,
  isomorphism: IsomorphismVis,
  mono: MonoVis,
  epi: EpiVis,
  terminal: TerminalVis,
  product: ProductVis,
  coproduct: CoproductVis,
  pullback: PullbackVis,
  equalizer: EqualizerVis,
  functor: FunctorVis,
  natural: NaturalVis,
  adjunction: AdjunctionVis,
  limits: LimitsVis,
  monad: MonadVis,
  yoneda: YonedaVis,
  ccc: CCCVis,
  monoidal: MonoidalVis,
  string: StringVis,
  applicative: ApplicativeVis,
  profunctor: ProfunctorVis,
  comonad: ComonadVis,
  kan: KanVis,
  presheaf: PresheafVis,
  abelian: AbelianVis,
};
