import {
  SigmoidVis,
  TanhVis,
  BinaryStepVis,
  ReLUVis,
  LeakyReLUVis,
  ELUVis,
  SELUVis,
  PReLUVis,
  GELUVis,
  SwishVis,
  MishVis,
  HardswishVis,
  SoftmaxVis,
  SoftplusVis,
  SoftsignVis,
  IdentityVis,
} from "./activationFunctionsVisuals";

export const VIS_MAP = {
  sigmoid:      SigmoidVis,
  tanh:         TanhVis,
  "binary-step": BinaryStepVis,
  relu:         ReLUVis,
  "leaky-relu": LeakyReLUVis,
  elu:          ELUVis,
  selu:         SELUVis,
  prelu:        PReLUVis,
  gelu:         GELUVis,
  swish:        SwishVis,
  mish:         MishVis,
  hardswish:    HardswishVis,
  softmax:      SoftmaxVis,
  softplus:     SoftplusVis,
  softsign:     SoftsignVis,
  identity:     IdentityVis,
};
